config/routes.rb
Rails.application.routes.draw do
  resources :users

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out
  
  root "home#index"
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	
	#relationships
	has_many :captains

	#validations
	validates :username, presence: true, if: :username
	validates :email, presence: true,
										uniqueness: true,
										if: :email

	validates_presence_of :password, if: :password, :on => :create
	validates_confirmation_of :password

	#before actions
	before_save :encrypt_password, :unless => Proc.new { |u| u.password.blank? }
	before_save { self.email = email.downcase }

	def to_s
		self.username
	end

	def encrypt_password
		self.password_salt = BCrypt::Engine.generate_salt
		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	end

  def self.authenticate(email, password)
  	#need to change this over to username - Maybe either/or?
	  user = User.where(:email => email).first
	  if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	  	user
	  else
	  	nil
	  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def user_signed_in?
		if session[:user_id]
			true
		else
			false
		end
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user
	helper_method :user_signed_in?
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		#need to change this over to username
		@user = User.authenticate(params[:sessions][:email], params[:sessions][:password])
		
		if @user
			flash[:notice] = "You've been logged in."
			session[:user_id] = @user.id
			redirect_to "/"
		else
			flash[:alert] = "There was a problem logging you in."
			redirect_to log_in_path
		end

		
	end

	def edit
	end

	def show
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You've been logged out successfully."
		redirect_to "/"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update]

	def create
		@user = User.new(user_params)
		
		if @user.save
			flash[:notice] = "Account Created Successfully!"
			session[:user_id] = @user.id
			redirect_to root_path
		else
			flash[:alert] = "There was a problem creating your account. Please try again."
			redirect_to :back
		end
	end

	def index
		@users = User.all
	end

	def edit
	end

	def show
	end

	# PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
   	new_params = user_params.delete_blanks!

  	respond_to do |format|
    if @user.update_attributes(new_params)
    	format.html { redirect_to edit_user_path(@user.id), notice: 'User was successfully updated.' }
      format.json { render :show, status: :ok, location: @user }
    else
      format.html { render :edit }
      format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
end

private
	def set_user
    @user = User.find(params[:id])
  end

	def user_params
		params.require(:user).permit(:email, :username, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
.container.well
	.col-md-6
		%h3 Template Site for Rails

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Template Site
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	
	%body
		%nav{ :class => "navbar navbar-inverse" }
			.container-fluid
				.navbar-header
					%button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
						%span.sr-only Toggle navigation
						%span.icon-bar
						%span.icon-bar
						%span.icon-bar
					%a.navbar-brand{ :href => "/" }	Template Site
				#bs-example-navbar-collapse-1.collapse.navbar-collapse
					%ul.nav.navbar-nav
						- if current_user
							- if current_user.admin
								%li.dropdown{:role => "presentation"}
									%a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
										Admin Functions
										%span.caret
									%ul.dropdown-menu{:role => "menu"}
										%li= link_to "Users", users_path
					%ul.nav.navbar-nav.navbar-right
						- if user_signed_in?
							%li= link_to "Logged in as #{current_user.username}", edit_user_path(current_user.id)
							%li= link_to "Logout", log_out_path
						- else
							%li= link_to "Sign up", new_user_path
							%li= link_to "Login", log_in_path
		


			- if notice
				%p{ :class => "alert alert-success" }
					= notice
			- if alert
				%p{ :class => "alert alert-danger" }
					= alert

		= yield

app/views/users/edit.html.haml
.container.well
	.col-md-6
		= simple_form_for @user, html: { method: :put } do |f|
			= f.error_notification
			= f.input :username
			= f.input :email
			
			= f.input :password
			= f.input :password_confirmation

			= f.button :submit, "Update"

app/views/users/index.html.haml
.container.well
	.col-md-6
		- if current_user
			- if current_user.admin
				%table.table.table-striped
					%tr
						%th User Name
						%th Email Address
						%th Admin?

					- @users.each do |user|
						%tr
							%td= link_to user.username, user_path(user.id)
							%td= user.email
							%td= user.admin

				= link_to "New User", new_user_path, :class => "btn btn-default"
			- else
				%h3 You must be an administrator to access this page.
		- else
			%h3 Please log in to continue.

app/views/users/new.html.haml
.container.well
	.col-md-6
		%h1 Create Account
			
		= simple_form_for User.new do |f|
			= f.input :username
			= f.input :email
			= f.input :password
			= f.input :password_confirmation

			= f.button :submit

app/views/users/show.html.haml
.container-fluid.well
	.col-md-6